services:
  bentopdf:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SIMPLE_MODE: false # false for default mode, true for simple mode
    container_name: bentopdf
    ports:
      - '3000:8080'
    restart: unless-stopped
